<a href="https://colab.research.google.com/github/umang0015/AI-Tools-Usage-And-Productivity-Analysis/blob/main/Project1_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AI TOOLS USAGE & PRODUCTIVITY ANALYSIS

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### 1. Analyze a real-world dataset of 30,000 employee records to understand how AI tools are being adopted across different industries and job roles

### 2. Perform data cleaning and preprocessing, including handling missing values, checking duplicates, converting data types, and detecting outliers

### 3. Conduct Exploratory Data Analysis (EDA) using NumPy, Pandas, Matplotlib, and Seaborn to discover patterns and relationships within the data.

### 4. Compare AI adoption across industries, company sizes, work modes (remote/on-site), and experience levels.

### 5. Generate actionable insights and recommendations to help organizations understand the benefits and trends of AI adoption in the workplace.

#### Importing the neccessary libraries

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Loading the dataset

In [4]:
df = pd.read_csv('/content/drive/MyDrive/AI Tools Productivity.csv')

#### Basic Data Understanding

In [5]:
df.head()

,Employee_ID,Age,Industry,Job_Role,Experience_Years,Company_Size,Remote_Work_Type,AI_Tools_Used,Daily_AI_Usage_Hours,Primary_AI_Tool,...,Meetings_Per_Day,Work_Hours_Per_Day,Job_Satisfaction,Productivity_Change,Salary_USD,Promotion_Last_Year,Fear_of_AI_Replacing_Job,Target,Date,DateTime
0,1,50.0,Tech,Consultant,14.0,Large,Onsite,2.0,3.9,Midjourney,...,6,4.3,High,Decreased,73423.0,No,Low,Low,2025-04-13,2025-04-13 13:27:24
1,2,NaN,Finance,Data Scientist,2.0,Large,Remote,4.0,4.8,Grok,...,3,5.1,Low,Same,60769.0,No,Low,Low,2025-12-15,2025-12-15 15:47:28
2,3,43.0,Marketing,Consultant,NaN,Small,Onsite,0.0,1.5,Midjourney,...,3,6.2,High,Increased,47189.0,No,Medium,Low,2025-09-28,2025-09-28 06:03:19
3,4,24.0,Retail,Software Developer,0.0,Medium,Remote,2.0,3.4,Gemini,...,0,9.8,Low,Same,39433.0,Yes,Low,High,2025-04-17,2025-04-17 18:00:56
4,5,30.0,Education,Consultant,4.0,Large,Onsite,1.0,3.4,Copilot,...,6,5.0,High,Decreased,39152.0,No,High,High,2025-03-13,2025-03-13 22:21:08

In [6]:
df.tail()

,Employee_ID,Age,Industry,Job_Role,Experience_Years,Company_Size,Remote_Work_Type,AI_Tools_Used,Daily_AI_Usage_Hours,Primary_AI_Tool,...,Meetings_Per_Day,Work_Hours_Per_Day,Job_Satisfaction,Productivity_Change,Salary_USD,Promotion_Last_Year,Fear_of_AI_Replacing_Job,Target,Date,DateTime
29995,29996,23.0,NaN,Software Developer,0.0,Small,Hybrid,3.0,1.7,Midjourney,...,7,10.0,Low,Same,46178.0,Yes,Low,Low,2025-12-28,2025-12-28 08:04:27
29996,29997,23.0,Healthcare,Manager,NaN,MNC,Remote,1.0,1.8,Gemini,...,3,9.1,High,Same,28349.0,No,High,Low,2025-11-16,2025-11-16 13:09:18
29997,29998,43.0,Marketing,Designer,10.0,Small,Hybrid,0.0,4.6,Midjourney,...,4,5.2,Medium,Decreased,47409.0,No,Medium,Low,2025-06-02,2025-06-02 13:20:59
29998,29999,32.0,Healthcare,Data Analyst,3.0,Small,Onsite,NaN,4.3,Claude,...,3,9.7,High,Decreased,46830.0,Yes,High,High,2025-08-02,2025-08-02 04:34:26
29999,30000,27.0,Education,Software Developer,4.0,Large,Hybrid,2.0,0.6,Claude,...,4,5.5,High,Decreased,42929.0,Yes,Low,Low,2025-11-04,2025-11-04 16:21:07

#### Checking Random Sample

In [7]:
df.sample(5)

,Employee_ID,Age,Industry,Job_Role,Experience_Years,Company_Size,Remote_Work_Type,AI_Tools_Used,Daily_AI_Usage_Hours,Primary_AI_Tool,...,Meetings_Per_Day,Work_Hours_Per_Day,Job_Satisfaction,Productivity_Change,Salary_USD,Promotion_Last_Year,Fear_of_AI_Replacing_Job,Target,Date,DateTime
18774,18775,33.0,Tech,Software Developer,7.0,Small,Onsite,3.0,4.8,Gemini,...,2,8.2,Low,Decreased,50596.0,No,Low,Low,2025-04-22,2025-04-22 03:10:48
29434,29435,49.0,Tech,Designer,24.0,MNC,Remote,0.0,4.2,Midjourney,...,1,9.2,High,Increased,90481.0,No,High,Low,2025-01-26,2025-01-26 17:59:15
29544,29545,40.0,Retail,Data Scientist,NaN,MNC,Onsite,4.0,0.1,Gemini,...,4,6.0,NaN,Decreased,71247.0,Yes,Medium,Low,2025-08-11,2025-08-11 10:38:02
3975,3976,53.0,Marketing,HR,15.0,Large,Onsite,3.0,3.0,ChatGPT,...,3,5.9,High,Decreased,64516.0,Yes,Medium,Low,2025-12-02,2025-12-02 19:59:32
14984,14985,22.0,Finance,Consultant,0.0,Small,Remote,1.0,NaN,Grok,...,3,6.2,Medium,Increased,37608.0,No,High,Low,2025-12-01,2025-12-01 10:12:31

#### Shape

In [8]:
df.shape

(30000, 23)

#### Column Names

In [9]:
df.columns

Index(['Employee_ID', 'Age', 'Industry', 'Job_Role', 'Experience_Years',
       'Company_Size', 'Remote_Work_Type', 'AI_Tools_Used',
       'Daily_AI_Usage_Hours', 'Primary_AI_Tool', 'Tasks_Automated_Percent',
       'Time_Saved_Per_Day_Minutes', 'Learning_Time_Per_Week_Hours',
       'Meetings_Per_Day', 'Work_Hours_Per_Day', 'Job_Satisfaction',
       'Productivity_Change', 'Salary_USD', 'Promotion_Last_Year',
       'Fear_of_AI_Replacing_Job', 'Target', 'Date', 'DateTime'],
      dtype='object')

#### Data Types

In [10]:
df.dtypes

Employee_ID                       int64
Age                             float64
Industry                         object
Job_Role                         object
Experience_Years                float64
Company_Size                     object
Remote_Work_Type                 object
AI_Tools_Used                   float64
Daily_AI_Usage_Hours            float64
Primary_AI_Tool                  object
Tasks_Automated_Percent           int64
Time_Saved_Per_Day_Minutes      float64
Learning_Time_Per_Week_Hours    float64
Meetings_Per_Day                  int64
Work_Hours_Per_Day              float64
Job_Satisfaction                 object
Productivity_Change              object
Salary_USD                      float64
Promotion_Last_Year              object
Fear_of_AI_Replacing_Job         object
Target                           object
Date                             object
DateTime                         object
dtype: object

#### Information of dataset

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Employee_ID                   30000 non-null  int64
 1   Age                           28497 non-null  float64
 2   Industry                      28553 non-null  object
 3   Job_Role                      30000 non-null  object
 4   Experience_Years              28506 non-null  float64
 5   Company_Size                  30000 non-null  object
 6   Remote_Work_Type              30000 non-null  object
 7   AI_Tools_Used                 28500 non-null  float64
 8   Daily_AI_Usage_Hours          28475 non-null  float64
 9   Primary_AI_Tool               30000 non-null  object
 10  Tasks_Automated_Percent       30000 non-null  int64
 11  Time_Saved_Per_Day_Minutes    28609 non-null  float64
 12  Learning_Time_Per_Week_Hours  30000 non-null  float64
 13  Meetings_Per_Day              30000 non-null  int64
 14  Work_Hours_Per_Day            28493 non-null  float64
 15  Job_Satisfaction              28518 non-null  object
 16  Productivity_Change           30000 non-null  object
 17  Salary_USD                    28542 non-null  float64
 18  Promotion_Last_Year           30000 non-null  object
 19  Fear_of_AI_Replacing_Job      30000 non-null  object
 20  Target                        30000 non-null  object
 21  Date                          30000 non-null  object
 22  DateTime                      30000 non-null  object
dtypes: float64(8), int64(3), object(12)
memory usage: 5.3+ MB

#### Statistical Summary

In [12]:
df.describe()

,Employee_ID,Age,Experience_Years,AI_Tools_Used,Daily_AI_Usage_Hours,Tasks_Automated_Percent,Time_Saved_Per_Day_Minutes,Learning_Time_Per_Week_Hours,Meetings_Per_Day,Work_Hours_Per_Day,Salary_USD
count,30000.000000,28497.000000,28506.000000,28500.000000,28475.000000,30000.000000,28609.000000,30000.000000,30000.000000,28493.000000,28542.000000
mean,15000.500000,38.046110,8.023609,1.996105,2.503533,39.305200,89.656612,2.993697,3.507167,6.998186,57066.542043
std,8660.398374,9.538593,7.400866,1.409250,1.441564,23.060026,52.079710,1.737679,2.297402,1.733020,16452.860788
min,1.000000,22.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,25022.000000
25%,7500.750000,30.000000,2.000000,1.000000,1.300000,19.000000,44.000000,1.500000,1.000000,5.500000,44902.000000
50%,15000.500000,38.000000,6.000000,2.000000,2.500000,39.000000,89.000000,3.000000,4.000000,7.000000,54117.000000
75%,22500.250000,46.000000,13.000000,3.000000,3.700000,59.000000,135.000000,4.500000,6.000000,8.500000,66891.500000
max,30000.000000,54.000000,32.000000,4.000000,5.000000,79.000000,179.000000,6.000000,7.000000,10.000000,120549.000000

Employee_ID -->  Unique identifier assigned to each employee.

Age	 -->   Age of the employee in years.

Gender -->  Gender of the employee.

Industry --> Industry in which the employee works (e.g., IT, Finance, Healthcare).

Job_Role -->	Employee's job designation or role.

Company_Size -->	Size of the organization (Small, Medium, Large).

Experience_Years -->	Total years of professional experience.

Salary_USD -->	Annual salary of the employee in US Dollars.

Primary_AI_Tool -->   The AI tool most frequently used by the employee.

AI_Tools_Used -->	Total number of AI tools used regularly.

Daily_AI_Usage_Hours -->	Average number of hours spent using AI tools per day.

Productivity_Score -->	Employee productivity score based on performance metrics.

Job_Satisfaction -->	Employee satisfaction level with their job.

Promotion_Status -->	Indicates whether the employee received a promotion.

Remote_Work -->	Work mode (Remote, Hybrid, or On-site).

Training_Hours -->	Number of AI-related training hours completed. (if present)

Time_Saved_Per_Week -->	Estimated hours saved each week due to AI usage. (if present)

Performance_Rating -->	Employee performance rating. (if present)

Date -->	Date on which the record was captured

DateTime -->	Complete timestamp including date and time.

Department/Location (if present) -->	Department or office location of the employee.

## Data Exploration and Data Cleaning

#### Missing Values

##### Missing values are identified to determine which columns require cleaning before analysis

In [13]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
      .str.replace(r"[()]","",regex=True)
)

In [14]:
df.columns

Index(['employee_id', 'age', 'industry', 'job_role', 'experience_years',
       'company_size', 'remote_work_type', 'ai_tools_used',
       'daily_ai_usage_hours', 'primary_ai_tool', 'tasks_automated_percent',
       'time_saved_per_day_minutes', 'learning_time_per_week_hours',
       'meetings_per_day', 'work_hours_per_day', 'job_satisfaction',
       'productivity_change', 'salary_usd', 'promotion_last_year',
       'fear_of_ai_replacing_job', 'target', 'date', 'datetime'],
      dtype='object')

In [15]:
df.isnull().sum()

employee_id                        0
age                             1503
industry                        1447
job_role                           0
experience_years                1494
company_size                       0
remote_work_type                   0
ai_tools_used                   1500
daily_ai_usage_hours            1525
primary_ai_tool                    0
tasks_automated_percent            0
time_saved_per_day_minutes      1391
learning_time_per_week_hours       0
meetings_per_day                   0
work_hours_per_day              1507
job_satisfaction                1482
productivity_change                0
salary_usd                      1458
promotion_last_year                0
fear_of_ai_replacing_job           0
target                             0
date                               0
datetime                           0
dtype: int64

### Check Null Values Percentage

In [16]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

In [17]:
missing_percentage.sort_values(ascending=False)

daily_ai_usage_hours            5.083333
work_hours_per_day              5.023333
age                             5.010000
ai_tools_used                   5.000000
experience_years                4.980000
job_satisfaction                4.940000
salary_usd                      4.860000
industry                        4.823333
time_saved_per_day_minutes      4.636667
job_role                        0.000000
employee_id                     0.000000
remote_work_type                0.000000
company_size                    0.000000
tasks_automated_percent         0.000000
primary_ai_tool                 0.000000
meetings_per_day                0.000000
learning_time_per_week_hours    0.000000
productivity_change             0.000000
promotion_last_year             0.000000
fear_of_ai_replacing_job        0.000000
target                          0.000000
date                            0.000000
datetime                        0.000000
dtype: float64

#### Observation - This tells you which columns have the most missing values.

### Handling Missing Values Numerical

In [19]:
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

### Observation - Filtering out the Numerical columns and Categorical Columns

### Fill Missing Values in Categorical Values

In [25]:
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

#### Observation All numeric columns now have no missing values — every NaN has been replaced with the median of its respective column

In [27]:
df.isnull().sum()

employee_id                     0
age                             0
industry                        0
job_role                        0
experience_years                0
company_size                    0
remote_work_type                0
ai_tools_used                   0
daily_ai_usage_hours            0
primary_ai_tool                 0
tasks_automated_percent         0
time_saved_per_day_minutes      0
learning_time_per_week_hours    0
meetings_per_day                0
work_hours_per_day              0
job_satisfaction                0
productivity_change             0
salary_usd                      0
promotion_last_year             0
fear_of_ai_replacing_job        0
target                          0
date                            0
datetime                        0
dtype: int64

In [28]:
df[col] = df[col].fillna(df[col].mode()[0])

In [29]:
df.isnull().sum()

employee_id                     0
age                             0
industry                        0
job_role                        0
experience_years                0
company_size                    0
remote_work_type                0
ai_tools_used                   0
daily_ai_usage_hours            0
primary_ai_tool                 0
tasks_automated_percent         0
time_saved_per_day_minutes      0
learning_time_per_week_hours    0
meetings_per_day                0
work_hours_per_day              0
job_satisfaction                0
productivity_change             0
salary_usd                      0
promotion_last_year             0
fear_of_ai_replacing_job        0
target                          0
date                            0
datetime                        0
dtype: int64

In [30]:
df.duplicated().sum()

np.int64(0)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   employee_id                   30000 non-null  int64
 1   age                           30000 non-null  float64
 2   industry                      30000 non-null  object
 3   job_role                      30000 non-null  object
 4   experience_years              30000 non-null  float64
 5   company_size                  30000 non-null  object
 6   remote_work_type              30000 non-null  object
 7   ai_tools_used                 30000 non-null  float64
 8   daily_ai_usage_hours          30000 non-null  float64
 9   primary_ai_tool               30000 non-null  object
 10  tasks_automated_percent       30000 non-null  int64
 11  time_saved_per_day_minutes    30000 non-null  float64
 12  learning_time_per_week_hours  30000 non-null  float64
 13  meetings_per_day              30000 non-null  int64
 14  work_hours_per_day            30000 non-null  float64
 15  job_satisfaction              30000 non-null  object
 16  productivity_change           30000 non-null  object
 17  salary_usd                    30000 non-null  float64
 18  promotion_last_year           30000 non-null  object
 19  fear_of_ai_replacing_job      30000 non-null  object
 20  target                        30000 non-null  object
 21  date                          30000 non-null  object
 22  datetime                      30000 non-null  object
dtypes: float64(8), int64(3), object(12)
memory usage: 5.3+ MB

In [32]:
df.head(15)

,employee_id,age,industry,job_role,experience_years,company_size,remote_work_type,ai_tools_used,daily_ai_usage_hours,primary_ai_tool,...,meetings_per_day,work_hours_per_day,job_satisfaction,productivity_change,salary_usd,promotion_last_year,fear_of_ai_replacing_job,target,date,datetime
0,1,50.0,Tech,Consultant,14.0,Large,Onsite,2.0,3.9,Midjourney,...,6,4.3,High,Decreased,73423.0,No,Low,Low,2025-04-13,2025-04-13 13:27:24
1,2,38.0,Finance,Data Scientist,2.0,Large,Remote,4.0,4.8,Grok,...,3,5.1,Low,Same,60769.0,No,Low,Low,2025-12-15,2025-12-15 15:47:28
2,3,43.0,Marketing,Consultant,6.0,Small,Onsite,0.0,1.5,Midjourney,...,3,6.2,High,Increased,47189.0,No,Medium,Low,2025-09-28,2025-09-28 06:03:19
3,4,24.0,Retail,Software Developer,0.0,Medium,Remote,2.0,3.4,Gemini,...,0,9.8,Low,Same,39433.0,Yes,Low,High,2025-04-17,2025-04-17 18:00:56
4,5,30.0,Education,Consultant,4.0,Large,Onsite,1.0,3.4,Copilot,...,6,5.0,High,Decreased,39152.0,No,High,High,2025-03-13,2025-03-13 22:21:08
5,6,25.0,Education,Designer,1.0,MNC,Remote,1.0,2.8,Claude,...,1,6.4,Low,Increased,30995.0,No,High,Low,2025-07-08,2025-07-08 12:17:19
6,7,35.0,Marketing,Software Developer,7.0,Large,Remote,3.0,0.2,ChatGPT,...,7,6.1,High,Same,54331.0,Yes,High,Low,2025-01-21,2025-01-21 16:04:55
7,8,50.0,Tech,Data Scientist,14.0,Large,Remote,4.0,0.4,ChatGPT,...,3,5.8,Low,Decreased,80422.0,Yes,Low,Low,2025-04-13,2025-04-13 11:22:23
8,9,32.0,Finance,Software Developer,2.0,Medium,Onsite,0.0,3.6,Copilot,...,1,6.2,Medium,Decreased,35184.0,No,Medium,Low,2025-05-02,2025-05-02 17:22:39
9,10,49.0,Education,Data Analyst,6.0,Small,Hybrid,0.0,3.1,Claude,...,6,8.0,Medium,Increased,56115.0,No,Low,Low,2025-08-03,2025-08-03 06:40:03
10,11,43.0,Education,Software Developer,2.0,Large,Remote,0.0,1.9,ChatGPT,...,1,7.0,High,Decreased,41685.0,No,Low,Low,2025-11-27,2025-11-27 06:15:01
11,12,48.0,Marketing,Designer,8.0,Small,Onsite,1.0,0.1,Midjourney,...,6,6.9,Low,Increased,56383.0,No,Low,Low,2025-03-29,2025-03-29 08:38:12
12,13,25.0,Finance,Data Analyst,1.0,Small,Onsite,4.0,1.2,Claude,...,4,4.5,High,Increased,48914.0,No,Medium,Low,2025-04-10,2025-04-10 22:21:59
13,14,43.0,Marketing,HR,1.0,Small,Hybrid,1.0,4.0,ChatGPT,...,3,5.1,Medium,Same,46157.0,No,High,High,2025-12-26,2025-12-26 08:16:08
14,15,32.0,Tech,Data Scientist,9.0,Large,Hybrid,3.0,1.8,Copilot,...,5,4.0,Medium,Same,61474.0,Yes,Low,Low,2025-06-01,2025-06-01 09:36:44